### ISSUE TITLE
Menu help > about error: ReferenceError: alert is not defined

### ISSUE THREAD

**Issue by josh-hemphill** [lukehaas/RunJS#229]
Clicking `Help` > `About` results in an error prompt.
```
A javascript error occurred in the main process

Uncaught Exception:
ReferenceError: alert is not defined
   at click(/opt/RunJS/resources/app.asar/entry-bundle.js:212:280099)
   at MenuItem.click (electron/js2c/browser_init.js:73:1683)
   at Object.a._executeCommand (electron/js2c/browser_init.js:81:2343)
```

Version: 1.14.1
OS: Ubuntu 20.04

**Comment by lukehaas** [comment]
This is now fixed in the latest release.
