### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by DavidWesley** [lukehaas/RunJS#285]
Error:
```Error: EPERM: operation not permitted, rename 'C:\Users\David\AppData\Roaming\runjs\config.json.tmp-734895673837e6c1' -> 'C:\Users\David\AppData\Roaming\runjs\config.json'
    at renameSync (fs.js:772:3)
    at n (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:123920)
    at Object.p [as writeFileSync] (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:122493)
    at e.exports._write (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:93707)
    at e.exports.set store [as store] (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:92298)
    at e.exports.set (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:91097)
    at BrowserWindow.<anonymous> (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:133273)
    at y (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:85054)
    at E (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:85329)
    at Timeout.k [as _onTimeout] (C:\Users\David\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:85219)
```
OS: Windows NT 10.0.19043

**Comment by lukehaas** [comment]
Thanks, @DavidWesley. Is this happening every time you open the app or just in some scenarios? 
Does this error prevent you from running the app?

**Comment by DavidWesley** [comment]
Just once, @lukehaas
