### ISSUE TITLE
Latest Run JS Version Error

### ISSUE THREAD

**Issue by Aamir2000** [lukehaas/RunJS#295]
I literally like 20 mins ago bought a license thinking run js is a cool software. As soon as I activated this product license all hell break lose and now everything started breaking and it started giving me all kinds of bugs and errors.

First of all when I try to change theme it shows this:
![image](https://user-images.githubusercontent.com/39049734/128604604-33c18add-22f4-451f-9aa6-4c591e79a9ef.png)

And then whenever I try to exit it...it shows a error window that just goes away right away before I even get a chance to screenshot it.

and the autocompletion feature doesn't work it doesn't even complete the thing it shows in the gif ( i.e Math object )

and when you go ahead and try to add a private and public field in class it says class fields are not enabled ( syntax error ) and there's no way to enable it....Now you might say this dude doesn't know what he's talking about js doesn't even support private fields or public fields in classes yet....or the keywords anyways....well I thought it supports typescripts right out of the box....

![image](https://user-images.githubusercontent.com/39049734/128604750-92db045b-1819-4ac3-a372-284399758082.png)
![image](https://user-images.githubusercontent.com/39049734/128604770-8531a1f7-4338-423a-9527-1e297c224db1.png)

Can I get a refund ? or at least an update that fixes all these issues ?

**Comment by lukehaas** [comment]
Hi @Aamir2000, I've not seen any of these errors you're seeing. Could you please try downloading the latest version and re-installing?

**Comment by lukehaas** [comment]
@Aamir2000 is it possible your config file for RunJS has been edited? That is the only explanation I can think of for the errors you're seeing.

**Comment by Aamir2000** [comment]
I have not edited any config files or any files related to runjs itself....I mean as I say that I didn't even knew a config file ever existed anywhere in this thing...but anyways I digress let me try and reinstall the latest version.

**Comment by Aamir2000** [comment]
Nope @lukehaas doesn't work at all... Either it stores config files somewhere else not in the folder root of the installation.

**Comment by lukehaas** [comment]
Please delete this file: `%APPDATA%\runjs\config.json` and then re-open the app.

Please also paste here the contents of your log files, located at `%APPDATA%\runjs\logs`

**Comment by OfficialAamir** [comment]
@lukehaas Here is my log file


`[2021-03-05 00:43:17.209] [info] Checking for update
[2021-03-05 00:43:17.492] [info] Generated new staging user ID: 3cb543a3-e693-5b00-a2f3-9d38b50ae57f
[2021-03-05 00:43:20.842] [info] Update for version 1.14.1 is not available (latest version: 1.14.1, downgrade is disallowed).
[2021-03-05 00:44:12.311] [info] Checking for update
[2021-03-05 00:44:15.313] [info] Update for version 1.14.1 is not available (latest version: 1.14.1, downgrade is disallowed).
[2021-03-05 00:47:04.792] [info] Checking for update
[2021-03-05 00:47:09.366] [info] Update for version 1.14.1 is not available (latest version: 1.14.1, downgrade is disallowed).
[2021-03-05 00:47:14.652] [info] Checking for update
[2021-03-05 00:47:15.936] [info] Update for version 1.14.1 is not available (latest version: 1.14.1, downgrade is disallowed).
[2021-04-14 20:21:15.601] [info] Checking for update
[2021-04-14 20:21:21.958] [info] Found version 1.15.1 (url: RunJS-Setup-1.15.1.exe)
[2021-04-14 20:21:21.961] [info] Downloading update from RunJS-Setup-1.15.1.exe
[2021-04-14 20:21:22.029] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: TxH0Ook6p3veSDyMgGtcvEBzunZd7dMl1n2T7htXd51IWAhgVDShJppY+SWBwuzm9+3lSKf2/OctngqxCJWLhQ==, expected: y2jp5gLO41eZ7A8WkcsSFtpM2czMaQ5MND/a5n4w8+RKu1HCO3s1RItii/0wCgDoMoKkssGssBYjXmD4A0tqIA==. Directory for cached update will be cleaned
[2021-04-14 20:21:22.128] [info] Download block maps (old: "https://github.com/lukehaas/RunJS/releases/download/v1.14.1/RunJS-Setup-1.14.1.exe.blockmap", new: https://github.com/lukehaas/RunJS/releases/download/v1.15.1/RunJS-Setup-1.15.1.exe.blockmap)
[2021-04-14 20:21:23.503] [info] File has 3816 changed blocks
[2021-04-14 20:21:25.635] [info] Full: 83,778.71 KB, To download: 77,070.31 KB (92%)
[2021-04-14 20:21:25.658] [info] Differential download: https://github.com/lukehaas/RunJS/releases/download/v1.15.1/RunJS-Setup-1.15.1.exe
[2021-04-14 20:21:26.068] [info] Redirect to https://github-releases.githubusercontent.com/152989255/b67a1680-9ad8-11eb-8d39-d85713a3b9cf
[2021-04-14 20:21:41.745] [info] New version 1.15.1 has been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-1.15.1.exe
[2021-04-14 20:21:53.005] [info] Install on explicit quitAndInstall
[2021-04-14 20:21:53.008] [info] Install: isSilent: false, isForceRunAfter: true
[2021-04-14 20:21:54.117] [info] Update installer has already been triggered. Quitting application.
[2021-04-14 20:23:48.090] [info] Checking for update
[2021-04-14 20:23:51.567] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).
[2021-07-12 17:03:10.650] [info] Checking for update
[2021-07-12 17:03:16.364] [error] Error: Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7029)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-07-12 17:03:38.605] [info] Checking for update
[2021-07-12 17:03:38.626] [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7029)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-07-15 16:22:26.543] [info] Checking for update
[2021-07-15 16:22:31.948] [info] Found version 2.0.1 (url: RunJS-Setup-2.0.1.exe)
[2021-07-15 16:22:31.951] [info] Downloading update from RunJS-Setup-2.0.1.exe
[2021-07-15 16:22:32.191] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: y2jp5gLO41eZ7A8WkcsSFtpM2czMaQ5MND/a5n4w8+RKu1HCO3s1RItii/0wCgDoMoKkssGssBYjXmD4A0tqIA==, expected: 3ZSd27forC4O6M9+V+1/RE+UypQUtpiUofSQXO3VVVXrNyV+qi687rQ5yTVhuN+tdQVhpH5z+qAdO2zk5Dlehw==. Directory for cached update will be cleaned
[2021-07-15 16:22:32.231] [info] Download block maps (old: "https://github.com/lukehaas/RunJS/releases/download/v1.15.1/RunJS-Setup-1.15.1.exe.blockmap", new: https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-Setup-2.0.1.exe.blockmap)
[2021-07-15 16:22:33.107] [info] File has 2343 changed blocks
[2021-07-15 16:22:33.450] [info] Full: 81,310.39 KB, To download: 48,393.26 KB (60%)
[2021-07-15 16:22:33.601] [info] Differential download: https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-Setup-2.0.1.exe
[2021-07-15 16:22:33.936] [info] Redirect to https://github-releases.githubusercontent.com/152989255/c341eb80-d67f-11eb-8579-a634b55d8fc5
[2021-07-15 16:22:44.990] [info] New version 2.0.1 has been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.0.1.exe
[2021-07-15 16:22:50.071] [info] Auto install update on quit
[2021-07-15 16:22:50.073] [info] Install: isSilent: true, isForceRunAfter: false
[2021-07-15 16:25:35.812] [info] Checking for update
[2021-07-15 16:25:40.020] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).
[2021-08-02 17:45:12.592] [info] Checking for update
[2021-08-02 17:45:13.020] [info] Checking for update (already in progress)
[2021-08-02 17:45:16.893] [info] Found version 2.1.1 (url: RunJS-Setup-2.1.1.exe)
[2021-08-02 17:45:18.592] [info] Downloading update from RunJS-Setup-2.1.1.exe
[2021-08-02 17:45:18.626] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: 3ZSd27forC4O6M9+V+1/RE+UypQUtpiUofSQXO3VVVXrNyV+qi687rQ5yTVhuN+tdQVhpH5z+qAdO2zk5Dlehw==, expected: 1ldCjx4zTX2maXXkfqb5xH3e/MbuFwCizpxXPBLr8UzGPr/rGVhgSojEG7gjmvyoF/wyh8YnaYSG+Y5ePHte6Q==. Directory for cached update will be cleaned
[2021-08-02 17:45:18.662] [info] Download block maps (old: "https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-Setup-2.0.1.exe.blockmap", new: https://github.com/lukehaas/RunJS/releases/download/v2.1.1/RunJS-Setup-2.1.1.exe.blockmap)
[2021-08-02 17:45:19.453] [info] File has 4108 changed blocks
[2021-08-02 17:45:19.583] [info] Full: 90,814.64 KB, To download: 84,152.99 KB (93%)
[2021-08-02 17:45:19.624] [info] Differential download: https://github.com/lukehaas/RunJS/releases/download/v2.1.1/RunJS-Setup-2.1.1.exe
[2021-08-02 17:45:19.923] [info] Redirect to https://github-releases.githubusercontent.com/152989255/ee080e75-b047-401e-90c2-bab90deb327a
[2021-08-02 17:45:30.860] [info] New version 2.1.1 has been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.1.1.exe
[2021-08-02 17:45:34.045] [info] Install on explicit quitAndInstall
[2021-08-02 17:45:34.047] [info] Install: isSilent: false, isForceRunAfter: true
[2021-08-02 17:45:37.009] [info] Update installer has already been triggered. Quitting application.
[2021-08-02 17:48:18.140] [info]  Checking for update
[2021-08-02 17:48:20.138] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-07 20:03:21.506] [info] Checking for update
[2021-08-07 20:03:25.580] [info] Found version 2.1.1 (url: RunJS-Setup-2.1.1.exe)
[2021-08-07 20:03:25.582] [info] Downloading update from RunJS-Setup-2.1.1.exe
[2021-08-07 20:03:27.196] [info] Update has already been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.1.1.exe).
[2021-08-07 20:03:34.204] [info] Auto install update on quit
[2021-08-07 20:03:34.208] [info] Install: isSilent: true, isForceRunAfter: false
[2021-08-07 20:04:31.785] [info] Checking for update
[2021-08-07 20:04:35.065] [info] Found version 2.1.1 (url: RunJS-Setup-2.1.1.exe)
[2021-08-07 20:04:35.067] [info] Downloading update from RunJS-Setup-2.1.1.exe
[2021-08-07 20:04:36.244] [info] Update has already been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.1.1.exe).
[2021-08-07 20:04:50.204] [info] Install on explicit quitAndInstall
[2021-08-07 20:04:50.208] [info] Install: isSilent: false, isForceRunAfter: true
[2021-08-07 20:04:50.343] [info] Update installer has already been triggered. Quitting application.
[2021-08-07 20:05:23.155] [info] Install on explicit quitAndInstall
[2021-08-07 20:05:23.586] [error] Error: Error: No valid update available, can't quit and install
    at g.install (E:\Softwares\runjs\resources\app.asar\entry-bundle.js:9:78922)
    at g.quitAndInstall (E:\Softwares\runjs\resources\app.asar\entry-bundle.js:9:78442)
    at t.quitAndInstall (E:\Softwares\runjs\resources\app.asar\entry-bundle.js:9:52443)
    at IpcMainImpl.<anonymous> (E:\Softwares\runjs\resources\app.asar\entry-bundle.js:135:60532)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
    at Object.emit (events.js:315:20)
[2021-08-07 20:05:24.415] [info] Checking for update
[2021-08-07 20:05:30.392] [info] Found version 2.1.1 (url: RunJS-Setup-2.1.1.exe)
[2021-08-07 20:05:30.394] [info] Downloading update from RunJS-Setup-2.1.1.exe
[2021-08-07 20:05:31.455] [info] Update has already been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.1.1.exe).
[2021-08-07 20:05:40.763] [info] Install on explicit quitAndInstall
[2021-08-07 20:05:40.766] [info] Install: isSilent: false, isForceRunAfter: true
[2021-08-07 20:05:40.876] [info] Update installer has already been triggered. Quitting application.
[2021-08-07 20:06:46.415] [error] C:\Users\Aamir:2
Started on: 2021/01/29 21:45:12.214
        ^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

[2021-08-07 20:06:52.579] [info]  Checking for update
[2021-08-07 20:06:54.018] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-07 20:07:02.296] [info]  Checking for update
[2021-08-07 20:07:02.560] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-07 20:23:22.928] [error] UnhandledRejection Error: Invalid argument provided for port
    at e.exports (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:270876)
    at App.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:269158)
    at App.emit (events.js:327:22)
    at appMethod (electron/js2c/browser_init.js:69:1830)
    at Object.execute (electron/js2c/browser_init.js:69:5579)
    at MenuItem.click (electron/js2c/browser_init.js:73:1696)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
[2021-08-07 20:23:56.055] [error] C:\Users\Aamir:2
Started on: 2021/01/29 21:45:12.214
        ^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

[2021-08-07 20:23:59.588] [info]  Checking for update
[2021-08-07 20:24:02.769] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-07 20:24:10.881] [error] UnhandledRejection Error: Invalid argument provided for port
    at e.exports (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:270876)
    at App.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:269158)
    at App.emit (events.js:327:22)
    at BrowserWindow.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:133080)
    at BrowserWindow.emit (events.js:315:20)
[2021-08-07 20:25:05.334] [info] Checking for update
[2021-08-07 20:25:07.553] [info] Found version 2.1.1 (url: RunJS-Setup-2.1.1.exe)
[2021-08-07 20:25:07.555] [info] Downloading update from RunJS-Setup-2.1.1.exe
[2021-08-07 20:25:08.302] [info] Update has already been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.1.1.exe).
[2021-08-07 20:25:15.079] [info] Install on explicit quitAndInstall
[2021-08-07 20:25:15.082] [info] Install: isSilent: false, isForceRunAfter: true
[2021-08-07 20:25:15.184] [info] Update installer has already been triggered. Quitting application.
[2021-08-07 20:27:51.014] [error] C:\Users\Aamir:2
Started on: 2021/01/29 21:45:12.214
        ^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

[2021-08-07 20:27:55.271] [info]  Checking for update
[2021-08-07 20:27:57.804] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-07 20:28:46.240] [error] UnhandledRejection Error: Invalid argument provided for port
    at e.exports (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:270876)
    at App.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:269158)
    at App.emit (events.js:327:22)
    at BrowserWindow.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:133080)
    at BrowserWindow.emit (events.js:315:20)
[2021-08-07 20:29:17.018] [info] Checking for update
[2021-08-07 20:29:19.650] [info] Found version 2.1.1 (url: RunJS-Setup-2.1.1.exe)
[2021-08-07 20:29:19.651] [info] Downloading update from RunJS-Setup-2.1.1.exe
[2021-08-07 20:29:20.379] [info] Update has already been downloaded to C:\Users\Aamir Zaidi\AppData\Local\runjs-updater\pending\RunJS-Setup-2.1.1.exe).
[2021-08-07 20:30:08.248] [info] Install on explicit quitAndInstall
[2021-08-07 20:30:08.251] [info] Install: isSilent: false, isForceRunAfter: true
[2021-08-07 20:30:08.378] [info] Update installer has already been triggered. Quitting application.
[2021-08-07 20:33:09.659] [info]  Checking for update
[2021-08-07 20:33:10.029] [error] C:\Users\Aamir:2
Started on: 2021/01/29 21:45:12.214
        ^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

[2021-08-07 20:33:11.794] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-07 20:45:14.190] [error] UnhandledRejection Error: Invalid argument provided for port
    at e.exports (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:270876)
    at App.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:269158)
    at App.emit (events.js:327:22)
    at BrowserWindow.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:133080)
    at BrowserWindow.emit (events.js:315:20)
[2021-08-08 06:45:18.090] [error] C:\Users\Aamir:2
Started on: 2021/01/29 21:45:12.214
        ^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

[2021-08-08 06:45:23.685] [info]  Checking for update
[2021-08-08 06:45:26.550] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
[2021-08-08 06:50:48.229] [error] UnhandledRejection Error: Invalid argument provided for port
    at e.exports (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:270876)
    at App.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:223:269158)
    at App.emit (events.js:327:22)
    at BrowserWindow.<anonymous> (C:\Users\Aamir Zaidi\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:133080)
    at BrowserWindow.emit (events.js:315:20)
`

**Comment by lukehaas** [comment]
Thanks for this. Did deleting the config.json help?

**Comment by OfficialAamir** [comment]
Sorry for late reply, No it didn't do anything I wish I could show you the error that comes up when I close this thing...but it just goes away way too quick...I just read a very small part of that message it mentions something about the port

**Comment by lukehaas** [comment]
@OfficialAamir from looking at your error log and doing some investigation, I have discovered that there is a problem related to you having a space in your user directory path. This seems to just be a Windows issue.
I'm working on a fix and I should have an update for you later this week.

**Comment by lukehaas** [comment]
@OfficialAamir I've now pushed a pre-release with a fix for handling directory paths with spaces on Windows.
https://github.com/lukehaas/RunJS/releases/tag/v2.1.2

Please let me know if this works ok for you.

**Comment by OfficialAamir** [comment]
Wow thanks for the quick service it works flawlessly now...thanks @lukehaas ! you're awesome I really enjoyed using Run js for a long time now...its very cool to have a playground....any chance of making one for html and css playground ? that'd be cool to have to prototype a design for a simple element.

**Comment by lukehaas** [comment]
Excellent, thanks for confirming. 
An html/css playground is something I've thought about in the past but not got any firm plans. Good to know you're interested in such a thing though. 👍
