### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by neramos** [lukehaas/RunJS#304]
Error:
```Error: EPERM: operation not permitted, rename 'C:\Users\neram\AppData\Roaming\runjs\config.json.tmp-91295770234bac45' -> 'C:\Users\neram\AppData\Roaming\runjs\config.json'
    at renameSync (fs.js:772:3)
    at n (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:123920)
    at Object.p [as writeFileSync] (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:122493)
    at e.exports._write (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:93707)
    at e.exports.set store [as store] (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:92298)
    at e.exports.set (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:91097)
    at BrowserWindow.<anonymous> (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:133273)
    at y (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:85054)
    at E (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:85329)
    at Timeout.k [as _onTimeout] (C:\Users\neram\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:138:85219)
```
OS: Windows NT 10.0.18363

**Comment by lukehaas** [comment]
Thanks, @neramos. Could you provide a bit more info about the scenario that you saw this error in?

Do you see this error every time you open the app?
Did you see this error around the same time as updating to a new version of RunJS?
Did you see this error while performing any particular action?

**Comment by neramos** [comment]
Hi,

Do you see this error every time you open the app?
No, just happened onceDid you see this error around the same time as updating to a new version of RunJS?No
Did you see this error while performing any particular action?When opened RunJS
Regards


—



    On Monday, August 16, 2021, 01:08:02 PM GMT-3, Luke Haas ***@***.***> wrote:  
 
 


Thanks, @neramos. Could you provide a bit more info about the scenario that you saw this error in?

Do you see this error every time you open the app?
Did you see this error around the same time as updating to a new version of RunJS?
Did you see this error while performing any particular action?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lukehaas** [comment]
Thanks, could you please provide a copy of the RunJS log, located here: `%AppData%/runjs/logs` in your explorer.
