### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by jgonzvil** [lukehaas/RunJS#313]
Error:
```Error: The command is disabled and cannot be executed
    at u.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:11:86311)
    at Immediate._onImmediate (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:11:51310)
    at processImmediate (internal/timers.js:461:21)
```
OS: macOS 10.14

**Comment by lukehaas** [comment]
Closing due to no response.
