### ISSUE TITLE
The application crashes and I can't use it (on Mac)

### ISSUE THREAD

**Issue by ivanlolivier** [lukehaas/RunJS#328]
This is the debug clipboard:

```
[
  {
    "path": "/Users/ivan/Library/Logs/runjs/main.log",
    "lines": [
      "[2021-06-25 02:37:40.080] [info] Checking for update",
      "[2021-06-25 02:37:40.142] [info] Generated new staging user ID: 92a97c7f-eaf2-5453-b54d-29efe5037e57",
      "[2021-06-25 02:37:43.075] [info] Update for version 2.0.0 is not available (latest version: 2.0.0, downgrade is disallowed).",
      "[2021-06-26 14:06:53.437] [info] Checking for update",
      "[2021-06-26 14:06:55.292] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-26 14:06:55.302] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-26 14:07:06.143] [info] New version 2.0.1 has been downloaded to /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-26 14:07:06.446] [info] / requested",
      "[2021-06-26 14:07:06.471] [info] /1624727226160-7938.zip requested",
      "[2021-06-26 14:07:06.472] [info] /1624727226160-7938.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-26 14:07:11.740] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-26 21:11:58.172] [info] Checking for update",
      "[2021-06-26 21:11:59.985] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-26 21:11:59.989] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-26 21:12:00.358] [info] / requested",
      "[2021-06-26 21:12:00.362] [info] /1624752720004-5089.zip requested",
      "[2021-06-26 21:12:00.362] [info] /1624752720004-5089.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-26 21:12:05.699] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-27 01:23:42.978] [info] Checking for update",
      "[2021-06-27 01:23:44.785] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-27 01:23:44.789] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-27 01:23:45.142] [info] / requested",
      "[2021-06-27 01:23:45.146] [info] /1624767824797-7105.zip requested",
      "[2021-06-27 01:23:45.146] [info] /1624767824797-7105.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-27 01:23:50.454] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-27 06:57:20.011] [info] Checking for update",
      "[2021-06-27 06:57:21.758] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-27 06:57:21.761] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-27 06:57:22.139] [info] / requested",
      "[2021-06-27 06:57:22.143] [info] /1624787841769-4481.zip requested",
      "[2021-06-27 06:57:22.143] [info] /1624787841769-4481.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-27 06:57:27.428] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-27 11:40:31.072] [info] Checking for update",
      "[2021-06-27 11:40:32.888] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-27 11:40:32.891] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-27 11:40:33.267] [info] / requested",
      "[2021-06-27 11:40:33.270] [info] /1624804832900-9453.zip requested",
      "[2021-06-27 11:40:33.270] [info] /1624804832900-9453.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-27 11:40:38.528] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-27 15:49:53.943] [info] Checking for update",
      "[2021-06-27 15:49:55.724] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-27 15:49:55.727] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-27 15:49:56.085] [info] / requested",
      "[2021-06-27 15:49:56.088] [info] /1624819795738-1585.zip requested",
      "[2021-06-27 15:49:56.089] [info] /1624819795738-1585.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-27 15:50:01.356] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-27 20:27:38.654] [info] Checking for update",
      "[2021-06-27 20:27:40.529] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-27 20:27:40.533] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-27 20:27:40.895] [info] / requested",
      "[2021-06-27 20:27:40.898] [info] /1624836460543-1523.zip requested",
      "[2021-06-27 20:27:40.899] [info] /1624836460543-1523.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-27 20:27:46.161] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-28 01:57:32.032] [info] Checking for update",
      "[2021-06-28 01:57:33.822] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-28 01:57:33.825] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-28 01:57:34.179] [info] / requested",
      "[2021-06-28 01:57:34.184] [info] /1624856253835-8243.zip requested",
      "[2021-06-28 01:57:34.184] [info] /1624856253835-8243.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-28 01:57:39.440] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-28 06:46:33.403] [info] Checking for update",
      "[2021-06-28 06:46:35.211] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-28 06:46:35.213] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-28 06:46:35.593] [info] / requested",
      "[2021-06-28 06:46:35.596] [info] /1624873595220-9736.zip requested",
      "[2021-06-28 06:46:35.597] [info] /1624873595220-9736.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-28 06:46:40.874] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-28 11:23:49.017] [info] Checking for update",
      "[2021-06-28 11:23:50.753] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-28 11:23:50.758] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-28 11:23:51.122] [info] / requested",
      "[2021-06-28 11:23:51.126] [info] /1624890230768-1035.zip requested",
      "[2021-06-28 11:23:51.126] [info] /1624890230768-1035.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-28 11:23:56.395] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-06-28 16:07:34.860] [info] Checking for update",
      "[2021-06-28 16:07:39.621] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
      "[2021-06-28 16:07:39.623] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
      "[2021-06-28 16:07:40.098] [info] Update has already been downloaded to /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip).",
      "[2021-06-28 16:07:40.631] [info] / requested",
      "[2021-06-28 16:07:40.741] [info] /1624907260102-3887.zip requested",
      "[2021-06-28 16:07:40.742] [info] /1624907260102-3887.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
      "[2021-06-28 16:07:49.959] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
      "[2021-07-16 01:17:47.454] [info] Checking for update",
      "[2021-07-16 01:17:49.419] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
      "[2021-07-17 19:33:21.452] [info] Checking for update",
      "[2021-07-17 19:33:23.392] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
      "[2021-07-21 12:48:14.199] [info] Checking for update",
      "[2021-07-21 12:48:16.227] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
      "[2021-07-28 17:18:22.088] [info] Checking for update",
      "[2021-07-28 17:18:25.028] [info] Found version 2.1.1 (url: RunJS-2.1.1-universal-mac.zip, RunJS-2.1.1-universal.dmg)",
      "[2021-07-28 17:18:25.037] [info] Downloading update from RunJS-2.1.1-universal-mac.zip, RunJS-2.1.1-universal.dmg",
      "[2021-07-28 17:18:25.050] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: uO3wmY/SUcPnV1PriZzLEWF+F0Qk+R9HO2MDmr6gQQPcSDHe1nEZvwRSnvDA0UMSqJL+ktQMgRt3I0JynchXjQ==, expected: xzCHrvtQqgkvUXI5xUpJuZAiYsJrybKfclKcFEPPDjZzHC5SrQ+QRMLvCvmqZ0le9RxO2B9sOHg3XBeqzmDlYQ==. Directory for cached update will be cleaned",
      "[2021-07-28 17:18:35.706] [info] New version 2.1.1 has been downloaded to /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.1-universal-mac.zip",
      "[2021-07-28 17:18:35.844] [info] / requested",
      "[2021-07-28 17:18:35.858] [info] /1627503515717-560.zip requested",
      "[2021-07-28 17:18:35.858] [info] /1627503515717-560.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.1-universal-mac.zip",
      "[2021-07-28 17:18:41.322] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.1.1/RunJS-2.1.1-universal-mac.zip)",
      "[2021-07-29 19:07:42.708] [info]  Checking for update",
      "[2021-07-29 19:07:44.538] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-04 19:03:02.458] [info]  Checking for update",
      "[2021-08-04 19:03:04.352] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-17 17:33:51.422] [info]  Checking for update",
      "[2021-08-17 17:33:52.891] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-23 12:47:27.337] [info]  Checking for update",
      "[2021-08-23 12:47:28.875] [info]  Found version 2.1.3 (url: RunJS-2.1.3-universal-mac.zip, RunJS-2.1.3-universal.dmg)",
      "[2021-08-23 12:47:28.876] [info]  Downloading update from RunJS-2.1.3-universal-mac.zip, RunJS-2.1.3-universal.dmg",
      "[2021-08-23 12:47:28.880] [info]  Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: xzCHrvtQqgkvUXI5xUpJuZAiYsJrybKfclKcFEPPDjZzHC5SrQ+QRMLvCvmqZ0le9RxO2B9sOHg3XBeqzmDlYQ==, expected: TfD0IKnb+Q5fbZZjX4+0eLjqJEnFbYfvF7gCdsP4fJcCanr84CLFOktGOgWzoXYBxqtthpGymGu6hw7DAllutg==. Directory for cached update will be cleaned",
      "[2021-08-23 12:47:38.527] [info]  New version 2.1.3 has been downloaded to /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.3-universal-mac.zip",
      "[2021-08-23 12:47:38.572] [info]  / requested",
      "[2021-08-23 12:47:38.576] [info]  /1629733658531-969.zip requested",
      "[2021-08-23 12:47:38.576] [info]  /1629733658531-969.zip requested by Squirrel.Mac, pipe /Users/ivan/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.3-universal-mac.zip",
      "[2021-08-23 12:47:43.816] [info]  Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.1.3/RunJS-2.1.3-universal-mac.zip)",
      "[2021-09-06 00:40:01.833] [error]",
      "[2021-09-08 14:05:49.464] [error] TypeError: Cannot read property 'classList' of null",
      "    at e._handleClickOutside (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:158:881776)",
      "[2021-09-09 02:23:33.402] [error] TypeError: Cannot read property 'classList' of null",
      "    at e._handleClickOutside (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:158:881776)",
      "[2021-09-09 02:27:11.482] [error] TypeError: Cannot read property 'classList' of null",
      "    at e._handleClickOutside (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:158:881776)",
      "[2021-09-09 15:41:40.880] [error] TypeError: Cannot read property 'classList' of null",
      "    at e._handleClickOutside (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:158:881776)",
      "[2021-09-10 05:44:01.770] [error]",
      "[2021-09-10 19:50:15.940] [error]",
      "[2021-09-10 19:51:28.866] [error]",
      "[2021-09-10 20:15:04.782] [error]",
      ""
    ]
  }
]
```

**Comment by lukehaas** [comment]
@ivanlolivier is this now closed because the issue is resolved? 
Could you tell me what the scenario was that caused the crash?

**Comment by ivanlolivier** [comment]
Hi @lukehaas! Yes, I closed the ticket because runJS is working fine now.

I don't know what exactly was causing the issue; I had 3 tabs opened, 2 of them with basic code and the other linked to a working directory. I tried a lot of things (I even restarted the computer) and now it's working fine. The last thing I tried was opening a new file form the file menu and it opened that file in the 3rd tab (replacing the previous content) 🤷‍♂️ 

If you need something else let me know.
