### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by amoterror** [lukehaas/RunJS#334]
Error:
```Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: Windows NT 10.0.19042

**Comment by lukehaas** [comment]
Thanks. Please upgrade to the latest version of RunJS.
