### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by Auraelius** [lukehaas/RunJS#391]
Error:
```Error: The command is disabled and cannot be executed
    at u.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:11:86311)
    at Immediate._onImmediate (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:11:51310)
    at processImmediate (internal/timers.js:461:21)
```
OS: macOS 10.17

This was after "Check for Updates..." and that confirmation dialog. after download, it asked if i wanted to quit and apply the update, i said yes, and this error appeared.

**Comment by lukehaas** [comment]
Thanks, this has been fixed in the latest version of RunJS.

**Comment by Auraelius** [comment]
Thanks. i downloaded and am happy.

This is a great product. I teach code school and mentor junior engineers at work. When there’s a question about the language, it is so easy to just throw RunJS up on the screen and run little experiments in a safe and clear environment until everybody’s got the behavioral info they need to make a choice. I use it the same way, especially for “duh!” stuff like “can I break a forEach()?”  For more complicated questions beyond the language, we use our codebase and our dev environment and that helps people get comfortable with those.

So many learners treats programming as if they are juggling knives, or priceless vases. Afraid to play ‘cos making a mistake in product code can mean a nasty cleanup. Product like yours help people become bold, to get comfortable with risks, to make little bets and experience little triumphs.Psychologically it’s tremendously powerful.

thanks again

**Comment by lukehaas** [comment]
Thanks! This is really great to hear, it's exactly the kind of benefit I hoped people would get out of using RunJS.

Would you mind if I quoted this on the website? https://runjs.app

**Comment by Auraelius** [comment]
Sure. please clean up the typos, tho. :-)

Al
