### ISSUE TITLE
[bug] Menu is not opening on click

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#433]
In v2.4.1, clicking on menu does nothing...

**Comment by lukehaas** [comment]
@shahul01 please provide details of what OS you're using and its version.

**Comment by shahul01** [comment]
windows 10 ver 1909

**Comment by lukehaas** [comment]
I have validated that this is working fine on Windows 10.
Please describe how you are clicking on the menu - which mouse buttons are you using, what part of the app are you clicking on, and also describe what you are expecting to see when clicking on this. If you could also provide screenshots that may be helpful.

**Comment by lukehaas** [comment]
@shahul01 any update?

**Comment by shahul01** [comment]
I am hibernating my PC so that may be it, if that's the case it will take a long time for me to properly restart windows to confirm so...


As for the screenshot, this is the best I could do.
I am using left mouse button to click on top left corner of app, and I expect to see a dropdown menu.
But when clicking, the button doesn't respond at all.
I tried to click using right mouse button and any setting hotkeys like ctrl p etc too just in case.

Let me know if you have any questions

![image](https://user-images.githubusercontent.com/53307156/171854099-bd3db8c8-5efb-4bf5-a5ef-d7f682155c81.png)

**Comment by shahul01** [comment]
So I restarted Windows, Uninstalled app, removed the RunJS folder in `appdata/Roaming`. ReInstalled it and still has same issue..

![image](https://user-images.githubusercontent.com/53307156/171999554-caa3738f-fed6-4d2a-87a8-bb34583b5167.png)

**Comment by lukehaas** [comment]
Ok, sorry to hear that. 
There might be some info in the log file that could be helpful, you can find this in `appdata/Roaming`, please paste the contents here.

**Comment by shahul01** [comment]
Its all the same error I think and shows whenever I click the menu


`[2022-06-04 18:14:24.545] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:25.008] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:25.958] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:29.580] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:29.811] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:29.983] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:30.161] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:32.259] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:33.296] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:33.538] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:14:33.830] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:25.816] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:26.317] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:26.690] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:26.691] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:27.398] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:27.619] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:27.810] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:27.811] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:27.862] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:28.001] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:28.002] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:28.095] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:30.648] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:31.092] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:31.280] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:31.445] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:31.613] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:31.788] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:16:31.962] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:17:03.883] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:17:04.128] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:17:04.468] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:17:04.664] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:17:04.836] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:55:05.496] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:55:06.066] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
[2022-06-04 18:55:06.486] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from 
    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)
    at IpcMainImpl.<anonymous> (C:\Users\shahul\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:8:71229)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
    at EventEmitter.emit (node:events:390:28)
`

**Comment by lukehaas** [comment]
Thanks,
I've also noticed that in your screenshots the button itself has an odd appearance, it should look like this:
![Screenshot 2022-06-04 at 14 53 53](https://user-images.githubusercontent.com/741344/172003840-3fbd72f8-6cfe-4c40-b629-624a9b3cade2.png)
With three evenly sized and spaced lines. It looks like the button is somehow being squashed or stretched for you.

I think the errors in your log might be referring to the x,y position that the menu is being set to - this is connected to the button size. Is it possible that some setting in your OS is affecting the size of this button?

**Comment by lukehaas** [comment]
I've just managed to replicate the issue by adjusting the system text size. It seems if the text size is set to anything larger than 100% then it causes the menu to be un-openable. 
I'll get this fixed in the next release. For now, you should be able to solve this by setting your system text-size to 100%.

**Comment by shahul01** [comment]
Thank you for solving this, appreciate it 😄

**Comment by lukehaas** [comment]
@shahul01 the latest release resolves this issue.
