### ISSUE TITLE
RunJS New AutoUpdate (OS-X - Ventura 13.3.1) Just hangs at the Upgrade Dialog

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#560]
![image](https://user-images.githubusercontent.com/57042275/233377243-5811232d-706d-4fd0-8ff2-04f56deddc28.png)

I can't tell why, it just has been sitting there for a very long time, with the progress bar looping over and over.

**Comment by lukehaas** [comment]
Thanks for raising this. Could you provide your debug log, please:
![Screenshot 2023-04-20 at 14 24 51](https://user-images.githubusercontent.com/741344/233380352-2f5b478a-070a-45a6-98b0-50b848818e9a.png)

**Comment by alankleindev** [comment]
Sure, thanks Luke.

{
  "version": "2.9.0",
  "platform": "darwin",
  "arch": "arm64",
  "activated": true,
  "logs": [
    {
      "path": "/Users/alan.klein/Library/Logs/runjs/main.log",
      "lines": [
        "[2022-06-14 22:45:46.745] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "[2022-06-14 22:45:47.206] [warn]  Error: Could not get code signature for running application",
        "    at Server.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:141642)",
        "    at Object.onceWrapper (node:events:513:28)",
        "    at Server.emit (node:events:394:28)",
        "    at emitListeningNT (node:net:1353:10)",
        "    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
        "[2022-06-14 22:45:47.209] [error] Error: Error: Could not get code signature for running application",
        "    at Server.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:141642)",
        "    at Object.onceWrapper (node:events:513:28)",
        "    at Server.emit (node:events:394:28)",
        "    at emitListeningNT (node:net:1353:10)",
        "    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
        "[2022-07-04 20:50:35.638] [error] Error: Error: net::ERR_NETWORK_CHANGED",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)",
        "    at SimpleURLLoaderWrapper.emit (node:events:390:28)",
        "[2022-07-04 20:50:35.641] [error] Unhandled Exception Error: net::ERR_NETWORK_CHANGED",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)",
        "    at SimpleURLLoaderWrapper.emit (node:events:390:28)",
        "[2022-07-21 18:25:45.950] [error]",
        "[2022-07-25 13:23:34.427] [error] Unhandled Exception Error: The 'screen' module can't be used before the app 'ready' event",
        "    at createScreenIfNeeded (node:electron/js2c/browser_init:125:261)",
        "    at Object.get (node:electron/js2c/browser_init:125:303)",
        "    at /Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:66163",
        "    at App.t.getOrCreateMainWindow (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:67502)",
        "    at App.emit (node:events:390:28)",
        "[2022-08-22 16:01:43.004] [error]",
        "[2022-08-25 12:14:49.845] [error]",
        "[2022-09-07 10:18:36.668] [error]",
        "[2022-09-07 10:19:50.042] [error]",
        "[2022-09-07 15:54:37.191] [error]",
        "[2022-09-07 15:58:23.883] [error]",
        "[2022-09-12 14:29:06.687] [error]",
        "[2022-10-12 14:34:37.464] [error]",
        "[2022-11-28 10:46:36.790] [error]",
        "[2022-12-15 15:03:51.246] [error]",
        "[2023-01-30 11:27:19.914] [error]",
        "[2023-01-30 15:37:25.358] [error]",
        "[2023-03-02 15:09:35.720] [error]",
        "[2023-03-22 19:43:09.134] [error]",
        "[2023-03-22 19:44:47.900] [error]",
        "[2023-03-24 09:38:03.129] [error]",
        "[2023-04-04 09:46:07.152] [error]",
        "[2023-04-07 16:44:21.253] [error]",
        "[2023-04-13 18:00:15.041] [error]",
        ""
      ]
    }
  ]
}

**Comment by lukehaas** [comment]
Thanks, @alankleindev. Unfortunately, there's not enough info to see what caused the issue, but I'll keep the ticket open in case anyone else encounters the same problem.

**Comment by lukehaas** [comment]
@alankleindev, a new version of RunJS has been released; if you've updated, did you encounter this issue again?

**Comment by alankleindev** [comment]
I upgraded RunJS on 3 machines. The upgrads went find on the Windows Machines. On the Mac with the latest version of OS-X, I got an error when I initiated the upgrade, maybe some permissions type issue? but when it closed and came up again, it was upgraded, so not sure what happened there. I didn't take any screenshot of the error though.

**Comment by lukehaas** [comment]
@alankleindev, thanks. Are you able to provide your debug log? There could be a record of the error there.

**Comment by alankleindev** [comment]
Yes, see below.

```
{
  "version": "2.10.1",
  "platform": "darwin",
  "arch": "arm64",
  "activated": true,
  "logs": [
    {
      "path": "/Users/alanklein/Library/Logs/runjs/main.log",
      "lines": [
        "[2023-11-30 20:43:55.798] [error]",
        "[2023-12-10 09:24:33.086] [error]",
        "[2023-12-12 17:56:50.750] [error]",
        "[2023-12-20 16:22:56.332] [warn]  Error: The command is disabled and cannot be executed",
        "    at l.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:146615)",
        "    at Immediate.O [as _onImmediate] (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:125769)",
        "    at process.processImmediate (node:internal/timers:476:21)",
        "[2023-12-20 16:22:56.335] [error] Error: Error: The command is disabled and cannot be executed",
        "    at l.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:146615)",
        "    at Immediate.O [as _onImmediate] (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:125769)",
        "    at process.processImmediate (node:internal/timers:476:21)",
        "[2023-12-20 16:23:03.433] [error] Error: Error: ENOENT: no such file or directory, rename '/Users/alanklein/Library/Application Support/Caches/runjs-updater/pending/temp-RunJS-2.10.1-universal-mac.zip' -> '/Users/alanklein/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.10.1-universal-mac.zip'",
        "[2023-12-20 16:23:03.434] [error] Error: ENOENT: no such file or directory, rename '/Users/alanklein/Library/Application Support/Caches/runjs-updater/pending/temp-RunJS-2.10.1-universal-mac.zip' -> '/Users/alanklein/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.10.1-universal-mac.zip'",
        "[2023-12-20 16:23:06.289] [error]",
        ""
      ]
    }
  ]
}
```
