### ISSUE TITLE
Checking for Updates, new Update Dialog reported over and over again

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#619]
When checking for the latest update, I get notified but the notification dialog keeps popping up over and over again after I click the OK button.

Then Error which I click OK to 3 times and then it closes and updated itself successfully.

<img width="314" alt="image" src="https://github.com/lukehaas/RunJS/assets/57042275/7c2e4ad6-a21d-436b-a354-6d9062041570">

<img width="269" alt="image" src="https://github.com/lukehaas/RunJS/assets/57042275/647a826f-5134-4ae4-913c-7062858ad386">

**Comment by lukehaas** [comment]
Thanks, @alankleindev. I'm not able to trigger this error myself.
It's very odd that these messages came up multiple times; that shouldn't be possible. 
Something really strange must have happened for this to occur. 

How do you usually quit the app? Had you had it running for long before triggering the update check?

**Comment by alankleindev** [comment]
I believe I had the app open always in the background. So I believe it is started automatically when I reboot my machine for updates or other reasons, if that helps. So I don't quit the app.

**Comment by alankleindev** [comment]
Here is some info from the runjs debug log for yesterdays timeframe:
```

       "[2024-04-24 08:38:03.468] [warn]  Error: The command is disabled and cannot be executed",
        "    at d.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:184435)",
        "    at Immediate._ [as _onImmediate] (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:122446)",
        "    at process.processImmediate (node:internal/timers:478:21)",
        "[2024-04-24 08:38:03.470] [error] Error: Error: The command is disabled and cannot be executed",
        "    at d.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:184435)",
        "    at Immediate._ [as _onImmediate] (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:122446)",
        "    at process.processImmediate (node:internal/timers:478:21)",
        "[2024-04-24 08:38:34.257] [warn]  Error: The command is disabled and cannot be executed",
        "    at d.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:184435)",
        "    at Immediate._ [as _onImmediate] (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:122446)",
        "    at process.processImmediate (node:internal/timers:478:21)",
        "[2024-04-24 08:38:34.258] [error] Error: Error: The command is disabled and cannot be executed",
        "    at d.quitAndInstall (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:184435)",
        "    at Immediate._ [as _onImmediate] (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:122446)",
        "    at process.processImmediate (node:internal/timers:478:21)",
        "[2024-04-24 08:38:34.345] [error] Error: Error: net::ERR_HTTP2_PROTOCOL_ERROR",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109574)",
        "    at SimpleURLLoaderWrapper.emit (node:events:514:28)",
        "    at SimpleURLLoaderWrapper.emit (node:domain:488:12)",
        "[2024-04-24 08:38:34.345] [error] download update Error: net::ERR_HTTP2_PROTOCOL_ERROR",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109574)",
        "    at SimpleURLLoaderWrapper.emit (node:events:514:28)",
        "    at SimpleURLLoaderWrapper.emit (node:domain:488:12)",
        "[2024-04-24 08:38:34.346] [error] Error: Error: net::ERR_HTTP2_PROTOCOL_ERROR",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109574)",
        "    at SimpleURLLoaderWrapper.emit (node:events:514:28)",
        "    at SimpleURLLoaderWrapper.emit (node:domain:488:12)",
        "[2024-04-24 08:38:34.346] [error] download update Error: net::ERR_HTTP2_PROTOCOL_ERROR",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109574)",
        "    at SimpleURLLoaderWrapper.emit (node:events:514:28)",
        "    at SimpleURLLoaderWrapper.emit (node:domain:488:12)",
        "[2024-04-25 14:38:19.516] [error] Unhandled TypeError: Cannot read properties of undefined (reading 'libraryDefaultDir')",
        "    at Function.resolvePathFn (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:97807)",
        "    at Function.readAllLogs (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:97314)",
        "    at click (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:90918)",
        "    at MenuItem.click (node:electron/js2c/browser_init:2:29559)",
        "    at a._executeCommand (node:electron/js2c/browser_init:2:34987)",
        ""
      ]
    }
  ]
}
```

**Comment by lukehaas** [comment]
Thanks, this is helpful 👍

**Comment by alankleindev** [comment]
The latest update worked for me :) No issues at all upgrading to Version 2.12.1 (2.12.1)
