### ISSUE TITLE
Check for Updates command resulted in error dialog.

### ISSUE THREAD

**Issue by AArnott** [lukehaas/RunJS#80]
I used Help -> Check for Updates in the 1.5.1 release and on top of the 'Found updates' dialog, this one appeared:

```
[Window Title]
Error

[Main Instruction]
Error: 

[Content]
Error: ENOENT: no such file or directory, rename 'C:\Users\andarno\AppData\Local\runjs-updater\pending\temp-runjs-setup-1.5.2.exe' -> 'C:\Users\andarno\AppData\Local\runjs-updater\pending\runjs-setup-1.5.2.exe'
    at F.U [as _captureStackTrace] (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:295113)
    at new f (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:324837)
    at C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:327926
    at e.NsisUpdater.doCheckForUpdates (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:15954)
    at e.NsisUpdater.checkForUpdates (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:12972)
    at e.NsisUpdater.checkForUpdatesAndNotify (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:13374)
    at e.initUpdater (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:265884)
    at Object.<anonymous> (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:18:244596)
    at n (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:203)
    at C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:996
    at Object.<anonymous> (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:1:1007)
    at Object.<anonymous> (C:\Users\andarno\AppData\Local\Programs\runjs\resources\app.asar\entry-bundle.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (C:\Users\andarno\AppData\Local\Programs\runjs\resources\electron.asar\browser\init.js:188:8)
    at Object.<anonymous> (C:\Users\andarno\AppData\Local\Programs\runjs\resources\electron.asar\browser\init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)

[OK]
```

_Originally posted by @AArnott in https://github.com/lukehaas/RunJS/issues/79#issuecomment-501429053_

**Comment by lukehaas** [comment]
Thanks, will look into this.

**Comment by lukehaas** [comment]
Closing as I've not been able to replicate this issue.
